
try{
	


}catch(error){
	console.log(error)
	alert("A ocurrido un error en el c√≥digo");
}
